name: CI/CD Laravel Docker (Prebuilt PHP+Nginx)

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --optimize-autoloader

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Todo-App
            docker compose up -d --remove-orphans
